# https://travis-ci.com/demosdemon/cookiecutter-python-project

dist: trusty
sudo: false

language: python
cache: pip

.mixins:
  - &xenial-mixin
    dist: xenial
    sudo: true
    addons:
      apt:
        packages:
          - libgnutls-dev

matrix:
  fast_finish: true
  include:
    - <<: *xenial-mixin
      name: Code-style check (black)
      python: "3.7"
      install:
        - pip install black
      script:
        - black --check --diff hooks tests
    - <<: *xenial-mixin
      name: Python imports check (isort)
      python: "3.7"
      install:
        - pip install isort
      script:
        - isort --check-only --diff --recursive hooks tests
    - <<: *xenial-mixin
      name: Flake8 static analysis
      python: "3.7"
      install:
        - pip install flake8
      script:
        - flake8 --show-source --statistics
    - name: py27 unit tests
      python: "2.7"
    - name: py34 unit tests
      python: "3.4"
    - name: py35 unit tests
      python: "3.5"
    - name: py36 unit tests
      python: "3.6"
    - <<: *xenial-mixin
      name: py37 unit tests
      python: "3.7"
    - <<: *xenial-mixin
      name: py38-dev unit tests
      python: "3.8-dev"
    - <<: *xenial-mixin
      name: pypy2 unit tests
      python: pypy2.7-6.0.0
    - <<: *xenial-mixin
      name: pypy3 unit tests
      python: pypy3.5-6.0.0

  allow_failures:
    - python: "3.8-dev"

install:
  - pip install -r requirements-dev.txt
  - pip install pytest-travis-fold
script:
  - py.test
