# https://travis-ci.com/demosdemon/cookiecutter-python-project

dist: trusty
sudo: false

language: python

.mixins:
  - &xenial-mixin
    dist: xenial
    sudo: true
    addons:
      apt:
        packages:
          - libgnutls-dev

matrix:
  fast_finish: true
  include:
    - python: "3.7"
      install:
        - pip install black
      script:
        - black --check --diff hooks tests
    - python: "3.7"
      install:
        - pip install isort
      script:
        - isort --check-only --diff --recursive hooks tests
    - python: "3.7"
      install:
        - pip install flake8
      script:
        - flake8 --show-source --statistics

    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - <<: *xenial-mixin
      python: "3.7"
    - <<: *xenial-mixin
      python: "3.8-dev"
    - python: pypy2.7-6.0.0
    - python: pypy3.5-6.0.0

  allow_failures:
    - python: "3.8-dev"

install:
  - pip install -r requirements-dev.txt
  - pip install pytest-travis-fold
script:
  - py.test
