# https://travis-ci.com/demosdemon/cookiecutter-python-project

sudo: false

language: python
cache: pip

dist: xenial
addons:
  apt:
    packages:
      - libgnutls-dev

matrix:
  fast_finish: true
  include:
    - name: Code-style check (black)
      python: "3.7"
      install:
        - pip install black
      script:
        - black --check --diff hooks tests
    - name: Python imports check (isort)
      python: "3.7"
      install:
        - pip install isort
      script:
        - isort --check-only --diff --recursive hooks tests
    - name: Flake8 static analysis
      python: "3.7"
      install:
        - pip install flake8
      script:
        - flake8 --show-source --statistics
    - name: py27 unit tests
      python: "2.7"
    - name: py34 unit tests
      python: "3.4"
    - name: py35 unit tests
      python: "3.5"
    - name: py36 unit tests
      python: "3.6"
    - name: py37 unit tests
      python: "3.7"
    - name: py38-dev unit tests
      python: "3.8-dev"
    - name: pypy2 unit tests
      python: pypy2.7-6.0.0
    - name: pypy3 unit tests
      python: pypy3.5-6.0.0

  allow_failures:
    - python: "3.8-dev"

install:
  - pip install -r requirements-test.txt
  - pip install pytest-travis-fold
script:
  - py.test
